version: "3"

services:
  app:
    image: navsim:latest
    build: .
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./simulations:/home/dev/simulations
      - ./resources/:/home/dev/.rviz2
    network_mode: host