#!/bin/bash

source install/setup.bash

trap 'kill -SIGINT $child_pids; wait $child_pids' SIGINT 

rqt & 
child_pids=$!
rviz2 &
child_pids="$child_pids $!"
ros2 launch nav_testbench nav_bringup.launch.py &
child_pids="$child_pids $!"

wait $child_pids