#!/bin/bash

source install/setup.bash

trap 'kill -SIGINT $child_pids; wait $child_pids' SIGINT 

rqt & 
child_pids=$!
rviz2 &
child_pids="$child_pids $!"
ros2 run simulation_loader simulation_loader &
child_pids="$child_pids $!"

wait $child_pids